#!/bin/bash
# to use this file:
# . cleanup 

make pretty
for f in *.c 
do
    sed -i "s/ b/0b/g" $f   # replace " b" with "0b"
done
for f in *.h 
do
    sed -i "s/ b/0b/g" $f   # replace " b" with "0b"
done
make clean
rm *~
